set(LIBIGL_INCLUDE_DIR "" CACHE FILEPATH "")
set(LIBIGL_LIBRARIES "" CACHE PATH "")
string(LENGTH "${LIBIGL_INCLUDE_DIR}" length)
if(NOT ${length} GREATER 0)
    message(FATAL_ERROR "LIBIGL_INCLUDE_DIR can't be empty")
endif()
string(LENGTH "${LIBIGL_LIBRARIES}" length)
if(NOT ${length} GREATER 0)
    message(FATAL_ERROR "LIBIGL_LIBRARIES can't be empty")
endif()
find_package(Eigen3 REQUIRED)
add_library(LibIGL INTERFACE)
target_include_directories(LibIGL INTERFACE ${LIBIGL_INCLUDE_DIR})
target_link_libraries(LibIGL INTERFACE Eigen3::Eigen)
# target_compile_definitions(LibIGL INTERFACE IGL_STATIC_LIBRARY)
# target_link_libraries(LibIGL INTERFACE ${LIBIGL_LIBRARIES})